name: bootme-backend

#services:
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
#    environment:
#      - node.name=es01
#      - cluster.name=es-docker-cluster
#      - discovery.type=single-node
#      - bootstrap.memory_lock=false
#      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
#      - xpack.security.enabled=false
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - esdata1:/usr/share/elasticsearch/data
#    ports:
#      - "9200:9200"
#    networks:
#      - esnet
#    healthcheck:
#      test: ["CMD-SHELL", "curl -s http://localhost:9200 | grep -q 'You Know, for Search'"]
#      interval: 20s
#      timeout: 10s
#      retries: 5

#  redis:
#    image: redis:7.0
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data
#    networks:
#      - esnet
#    healthcheck:
#      test: ["CMD", "redis-cli", "ping"]
#      interval: 10s
#      timeout: 5s
#      retries: 3

#networks:
#  esnet:
#
#volumes:
#  esdata1:
#    driver: local
#  redis_data:
#    driver: local
