domain: bootme.co.kr

spring:
  datasource:
    url: ENC(Iiho9QVZwoQ/VSqLn8ZAhZaO8jtKv1j0ssm/WLPelpwFglY6qbrsXBEFJHFmes0WVhX2/0MMNXKJxO4XDRgifxRH9a5BXKVbp0KleUJ6U/eDmRKqyuuonkIczkGCeNMxCHPhTbr6gNs=)
    username: ENC(Me7JQ99ri7Ufbh9eNwhY8Q==)
    password: ENC(0Jv/q2l5mIo6wOjZLyf/wZqVybziuXme)
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      leakDetectionThreshold: 10000
      maximum-pool-size: 20
  jpa:
    properties:
      open-in-view: false  # if true: SSE 커넥션 열려있는 동안 DB 커넥션도 열려있음 => Connection leak
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
      connection:
        characterEncoding: utf8mb4
        charSet: utf8mb4

server:
  servlet:
    session:
      cookie:
        domain: bootme.co.kr