domain: bootme.co.kr

spring:
  datasource:
    url: ENC(DH2p2uxp5rxc5XWG7j4JzBunWuN6Sj8eAWha7sEuQHgc5u8x+WBNmXSC91L7wszscoVfFA4H7ei1xa/SOvoUb2LGu6LBzFzmcVr13FXqHj9fG/cT1nIkG2Y3bSny4w3nWu5kqKeicKg=)
    username: ENC(Me7JQ99ri7Ufbh9eNwhY8Q==)
    password: ENC(0Jv/q2l5mIo6wOjZLyf/wZqVybziuXme)
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      leakDetectionThreshold: 10000
      maximum-pool-size: 20
  jpa:
    open-in-view: false  # if true: SSE 커넥션 열려있는 동안 DB 커넥션도 열려있음 => Connection leak
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
        default_batch_fetch_size: 100
      connection:
        characterEncoding: utf8mb4
        charSet: utf8mb4
  redis:
    host: ENC(4D3x72p+EQpt5L33Wi0w1Xm5abOKIbGshV/j2y0DEPLYV/q3X4PJHb5K1OXorsyGa00ZGR7w74Z9MlN1PsdQ/n/eId/7Zp96)
    port: 6379
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/prod
    baseline-version: 0

server:
  servlet:
    session:
      cookie:
        domain: bootme.co.kr