domain: localhost

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/bootme;MODE=MySQL
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE