logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

security:
  jwt:
    token:
      secret-key: ldrbJJuMmonBU4HNNjTkbftNYAtqVhxNC5P1b03KDiHckxnkeP4JHAHubg8tvLe2qekysibScVbegm_OVS0pL3OOQfUHaf-iiyjfM0UF5FPZqE9y693-voPz43XDBwbnAJErWEiER934V8kiJwiHfTQgFmOXM88A3H4eKf8eRo68RZHBhfKfdihB15kKG9e0C5Qyo43WktrE6UR-OoWRZdzk8hir5k7FYElv_JEFzOUCxqpMUW9PcQLBqfveuLsAswm2NPDfCdYS2nnSy4bASjvWxlWlG5uYHIVofD2yNeBuN1tCl3TLuZwzAumXoo5xrq8i2lTZh8sMrBq3oTLMOw
      expire-length:
        access: 3600000
        refresh: 1210000000