domain: bootme.co.kr

spring:
  datasource:
    url: ENC(Iiho9QVZwoQ/VSqLn8ZAhZaO8jtKv1j0ssm/WLPelpwFglY6qbrsXBEFJHFmes0WVhX2/0MMNXKJxO4XDRgifxRH9a5BXKVbp0KleUJ6U/eDmRKqyuuonkIczkGCeNMxCHPhTbr6gNs=)
    username: ENC(Me7JQ99ri7Ufbh9eNwhY8Q==)
    password: ENC(0Jv/q2l5mIo6wOjZLyf/wZqVybziuXme)
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 6
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
      connection:
        characterEncoding: utf8mb4
        charSet: utf8mb4

cloud:
  aws:
    s3:
      bucket: ENC(b8OwZ5ju4SzcnOBO92RwpWJwFe7nfdN6)
    credentials:
      access-key: ENC(2vctfEcCiuZ7RN87cOUTravlqHfd55Xe1s6zEKdLlzk=)
      secret-key: ENC(Koa+RVqWim1y9HryvbZ/ZE4T65fOjk1d+7IIrMQKDx1vuDcKJDaHIlbYAzDn/cseipNh/23YbvU=)
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

logback:
  access:
    config: classpath:logback-access.xml

management:
  endpoints:
    web:
      exposure:
        include: health

security:
  jwt:
    bootme:
      exp:
        millisecond:
          access: 3600000
          refresh: 2592000000