spring:
  datasource:
    url: ENC(j/ZDTGjL6xygc17oMFcG/Bx6YnYyiF40RK4I/+Ng4JgXM5Rg2zNnyXcotZgLWJQs70Lnup+K+JdbBp/ORbarlTWkrOh/8nfdiMDVA1XW6fzg39S01cB50ebF1KoSW4s+IHdU7atWB2hvdvLPBT6W75A59mhECzIsdQiihZMrzO1aS+EmdL0UAKqo0r7LuGmHmE8Ix2VNzu0=)
    username: ENC(vkHrR7So7NJxHyjHF8Irig==)
    password: ENC(OD0J7f1dvxrCcX/BQdNKM3q028KMcW7K)
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 6
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
      connection:
        characterEncoding: utf8mb4
        charSet: utf8mb4

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    org.hibernate.SQL: debug

security:
  jwt:
    bootme:
      issuer: https://bootme.back.com
      secret-key: ENC(zfPuFyzYA9XcPlEq0ntmMKo7kicPkh+lFL515nXcS72A8sqk0F4015ZPGb26Rj5i7j91yP4/SVSPPXt8M/DgumpXZf4999tKH0zv9tHF9nBvuKlYofc2nqUG3/+edaRP9F3VwpGCwtbNlO0Ob35dIkEd7le7oA+6rSrHlIUKDWSFe2ZNiDJf/h/sTV1bztHN40JYQ0VYbGYtMfWqxsHEH/BHg/NPJ5ASlPypJtFWJPvjtKxaQRoELaK/ubTdU9O2FAGmAI27Ry6LRT21tP68a6Yrw7AoTo5mz13cX8SaWKlXtWEi0th5QaTftsQKqZm6D6rkw1xDnuWDzTGvdG4eowUPN9VIwAz+VK8fJ/3H0EuhSVh8fTp6zHun1LuwqO8/7oyHtP8zljFc7I2kctpv3HaJMK0vr+tFUB+umDTRP2/tw8Bxrvy1rYVfDuwYYU4vU76r+oujHP5twxn3h1NW2g==)
      exp:
        millisecond:
          access: 3600000
          refresh: 2592000000
        second:
          access: 3600
          refresh: 2592000
    bootme_front:
      issuer: https://bootme.front.com
      audience: bootme.com
      secret-key: ENC(VmdR1XXp7UZ2vfrrhyOFpNydC+s76kzXroDXmG5GDzKBO61SFvLDyQrig7LkXoFSGwnb4hCzVm8wFxlbnNFZWlSnHhIfHUV1jYjhdwn/KEc=)
    google:
      issuer: https://accounts.google.com
      audience: ENC(MO/U9kPW/lSGM4vglHPQXNBMnlRLIwh8RlYlCYslxzaf86QdTm6iOiKAtMYHtrsAR0wE18Sk55SEZjBjK2ATSTqDRq6pzH9DLG+UozTzHTN+SwtU7nXpqA==)
    naver:
      issuer: https://bootme.front.com
      audience: ENC(ja0CnEC8rd485VzLWHaloyYk3fIU4kFxMfo3Ukxdpl7DbyVjiQygIg==)
      secret: ENC(EYkGqmVhUiOqcuNRl02ha0e5QHDb1+VlSDT31sZd+GaCfcoILVcGrFDoJNDBHQzO75fapRsHe533wkzX2G6x0sKf6JREwKKmBTLKmMQPePc8Z196MlyLm9nqVB4YYT+K)
    kakao:
      issuer: https://kauth.kakao.com
      audience: ENC(WK+mtafbv9GqIik6dY/LxpenM4CF7T5zz1z6MA0G4ysfdS5EBRcamVJwfGU+QaIv)