spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/bootme;MODE=MySQL
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: debug

security:
  jwt:
    issuer: bootme
    secret-key: ldrbJJuMmonBU4HNNjTkbftNYAtqVhxNC5P1b03KDiHckxnkeP4JHAHubg8tvLe2qekysibScVbegm_OVS0pL3OOQfUHaf-iiyjfM0UF5FPZqE9y693-voPz43XDBwbnAJErWEiER934V8kiJwiHfTQgFmOXM88A3H4eKf8eRo68RZHBhfKfdihB15kKG9e0C5Qyo43WktrE6UR-OoWRZdzk8hir5k7FYElv_JEFzOUCxqpMUW9PcQLBqfveuLsAswm2NPDfCdYS2nnSy4bASjvWxlWlG5uYHIVofD2yNeBuN1tCl3TLuZwzAumXoo5xrq8i2lTZh8sMrBq3oTLMOw
    exp:
      millisecond:
        access: 3600000
        refresh: 2592000000
      second:
        access: 3600
        refresh: 2592000