domain: bootme.co.kr

spring:
  datasource:
    url: ENC(W5ZcLN6fRBfq/DmucQvzZTlDigMi+pd+OnIBfUIiNXaq3iSe4xoFMaiXWE+31rD0QyCmd4B2YmihsCk0S7XvN72/wIKz3euNPeIzM9wmzQf5bBNnM47loh5PgAan1on2P5shNhwKFHM=)
    username: ENC(Me7JQ99ri7Ufbh9eNwhY8Q==)
    password: ENC(0Jv/q2l5mIo6wOjZLyf/wZqVybziuXme)
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      leakDetectionThreshold: 10000
      maximum-pool-size: 20
  jpa:
    open-in-view: false  # if true: SSE 커넥션 열려있는 동안 DB 커넥션도 열려있음 => Connection leak
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
      connection:
        characterEncoding: utf8mb4
        charSet: utf8mb4

server:
  servlet:
    session:
      cookie:
        domain: bootme.co.kr