domain: bootme.co.kr

spring:
  datasource:
    url: ENC(0YuQ00lAMM4AD+1F4F2yv+kaTUSKjATPEAZqdX9eUt39MyHc8T3nubBaflGKBYdM+7CFJV2pYlh3vrYIcjAQnFLaVEwc1SpeTBXqaNFNKGSi1qSuDl9i6mc1/Qip8p384az6tcEwUUg=)
    username: ENC(Me7JQ99ri7Ufbh9eNwhY8Q==)
    password: ENC(0Jv/q2l5mIo6wOjZLyf/wZqVybziuXme)
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      leakDetectionThreshold: 10000
      maximum-pool-size: 20
#  data:
#    redis:
#      host: ENC(nI8w8hoaeD5tgiCepSt5Fkn/MTFqileX)
#      port: 6379
  jpa:
    open-in-view: false  # if true: SSE 커넥션 열려있는 동안 DB 커넥션도 열려있음 => Connection leak
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: com.bootme.config.CustomDialect
        format_sql: true
        default_batch_fetch_size: 100
      connection:
        characterEncoding: utf8mb4
        charSet: utf8mb4
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/prod
    baseline-version: 0

#elasticsearch:
#  host: ENC(Y6X2hrLyMNMyV4IJs8XBmpHcrxSvaVgI)
#  port: 9200
#  username: ENC(dY9LzRN0RqiuzlXYD4vBYA==)
#  password: ENC(PxrTjPFz/BfnTymvst17eLObLyJEyRz4)

server:
  servlet:
    session:
      cookie:
        domain: bootme.co.kr
