allowed-origins: http://localhost:3000,http://localhost:3001,http://localhost:63342,https://bootme.co.kr,https://www.bootme.co.kr,https://staging.bootme.co.kr,https://api.bootme.co.kr,https://staging.api.bootme.co.kr

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  mvc:
    async:
      request-timeout: 120000

cloud:
  aws:
    credentials:
      access-key: ENC(2vctfEcCiuZ7RN87cOUTravlqHfd55Xe1s6zEKdLlzk=)
      secret-key: ENC(Koa+RVqWim1y9HryvbZ/ZE4T65fOjk1d+7IIrMQKDx1vuDcKJDaHIlbYAzDn/cseipNh/23YbvU=)

security:
  jwt:
    bootme:
      exp:
        millisecond:
          access: 3600000
          refresh: 2592000000

logback:
  access:
    config: classpath:logback-access.xml

decorator:
  datasource:
    p6spy:
      enable-logging: false

management:
  endpoints:
    web:
      exposure:
        include: 'health,info,metrics,prometheus'
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      hikaricp: true
      jvm: true
