domain: localhost

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/bootme;MODE=MySQL
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

logback:
  access:
    config: classpath:logback-access.xml

security:
  jwt:
    bootme:
      exp:
        millisecond:
          access: 3600000
          refresh: 2592000000