domain: bootme.co.kr

spring:
  datasource:
    url: ENC(Iiho9QVZwoQ/VSqLn8ZAhZaO8jtKv1j0ssm/WLPelpwFglY6qbrsXBEFJHFmes0WVhX2/0MMNXKJxO4XDRgifxRH9a5BXKVbp0KleUJ6U/eDmRKqyuuonkIczkGCeNMxCHPhTbr6gNs=)
    username: ENC(Me7JQ99ri7Ufbh9eNwhY8Q==)
    password: ENC(0Jv/q2l5mIo6wOjZLyf/wZqVybziuXme)
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
      connection:
        characterEncoding: utf8mb4
        charSet: utf8mb4

management:
  endpoints:
    web:
      exposure:
        include: health