domain: bootme.co.kr

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      leakDetectionThreshold: 10000
      max-lifetime: 300000   # 5분
      idle-timeout: 240000   # 4분
      keepalive-time: 120000   # 2분
      validation-timeout: 5000
      connection-timeout: 10000
#  data:
#    redis:
#      host: ENC(jEvMbZFxfZLTb0i42wiZKQelUtpPn1+yZnS0qInY4dkyYqKCdvZTxb2gNvaIABtbCMxa22+X0OLWeFpRMWusJ0cH5CeF36lH)
#      port: 6379
  jpa:
    open-in-view: false  # if true: SSE 커넥션 열려있는 동안 DB 커넥션도 열려있음 => Connection leak
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: core
        default_batch_fetch_size: 100
  flyway:
    schemas: core
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/staging
    baseline-version: 0

#elasticsearch:
#  host: ENC(lguxyL/JPPQK468m451LZ60q7psQsSuk)
#  port: 9200
#  username: ENC(dY9LzRN0RqiuzlXYD4vBYA==)
#  password: ENC(PxrTjPFz/BfnTymvst17eLObLyJEyRz4)

server:
  servlet:
    session:
      cookie:
        domain: bootme.co.kr

# backend/src/main/java/com/bootme/config/AwsSecretsConfig.java
app:
  aws:
    profile: cac-sso-workloads-staging
    region: ap-northeast-2
    secrets-manager:
      secret-name: bootme
    s3:
      bucket-name: staging-bootme-application-images
