domain: bootme.co.kr

spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/bootme
    username: ${AURORA_POSTGRESQL_USERNAME}
    password: ${AURORA_POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      leakDetectionThreshold: 10000
      max-lifetime: 300000   # 5분
      idle-timeout: 240000   # 4분
      keepalive-time: 120000   # 2분
      validation-timeout: 5000
      connection-timeout: 10000
#  data:
#    redis:
#      host: ENC(nI8w8hoaeD5tgiCepSt5Fkn/MTFqileX)
#      port: 6379
  jpa:
    open-in-view: false  # if true: SSE 커넥션 열려있는 동안 DB 커넥션도 열려있음 => Connection leak
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: core
        default_batch_fetch_size: 100
  flyway:
    schemas: core
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/prod
    baseline-version: 0

#elasticsearch:
#  host: ENC(Y6X2hrLyMNMyV4IJs8XBmpHcrxSvaVgI)
#  port: 9200
#  username: ENC(dY9LzRN0RqiuzlXYD4vBYA==)
#  password: ENC(PxrTjPFz/BfnTymvst17eLObLyJEyRz4)

server:
  servlet:
    session:
      cookie:
        domain: bootme.co.kr

# backend/src/main/java/com/bootme/config/AwsSecretsConfig.java
app:
  aws:
    profile: cac-sso-workloads-prod
    region: ap-northeast-2
    secrets-manager:
      secret-name: bootme
    s3:
      bucket-name: prod-bootme-application-images
