domain: localhost

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/bootme;MODE=MySQL
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

cloud:
  aws:
    s3:
      bucket: ENC(b8OwZ5ju4SzcnOBO92RwpWJwFe7nfdN6)
    credentials:
      access-key: ENC(2vctfEcCiuZ7RN87cOUTravlqHfd55Xe1s6zEKdLlzk=)
      secret-key: ENC(Koa+RVqWim1y9HryvbZ/ZE4T65fOjk1d+7IIrMQKDx1vuDcKJDaHIlbYAzDn/cseipNh/23YbvU=)
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

logback:
  access:
    config: classpath:logback-access.xml

security:
  jwt:
    bootme:
      exp:
        millisecond:
          access: 3600000
          refresh: 2592000000