name: Post Backend Test Results as PR Comment

on:
  pull_request:
    branches: [main]
    paths: ["backend/**"]
    types: [opened]

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Seoul

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Replace Jasypt Password in main application.yml
        run: sed -i "s/encryptKey/${{ secrets.JASYPT_PASSWORD }}/g" ./src/main/resources/application.yml

      - name: Replace Jasypt Password in test application.yml
        run: sed -i "s/encryptKey/${{ secrets.JASYPT_PASSWORD }}/g" ./src/test/resources/application.yml

      - name: Build with Gradle
        run: ./gradlew bootJar
        
      - name: Post Test Results as PR Comment
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: '**/build/test-results/test/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Post Check Comment on Failed Test Lines
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          token: ${{ github.token }}
